### ISSUE TITLE
# 서버 인프라 세팅 진행

### ISSUE THREAD

**Issue by key-del-jeeinho** [EmoHipHop/mz2mo-server#1]
## 📚 Epic
서버 인프라 세팅 진행
## 🗂 Desc
향후 서버 어플리케이션 개발에 필요한 인프라 세팅을 수행해요.
이후 빠른 업데이트를 위한 CI/CD 자동화 프로세스를 구축하는것을 목표로해요.
## 🔍 Work
- [x] GCP 인프라 세팅 진행
- [x] Docker 관련 설정 진행
- [x] Jenkins CI/CD 파이프라인 구축
- [x] Server Application에 Jenkins, Docker 관련 설정 추가

**Comment by key-del-jeeinho** [comment]
CI/CD 파이프라인 구축 및 기타 인프라세팅 완료하였습니다.
